name: pack
on: [workflow_dispatch, push]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: "smallkai"
      - name: pack
        run: make all
      - name: upload artifact to github
        uses: actions/upload-artifact@v4
        with:
          name: Alas
          path: pack/Alas.zip
          if-no-files-found: error

